version: '3.1'

services:
  database:
    container_name: postgres-api-labs
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database-labs
