version: '3.1'

services:
  database:
    container_name: postgres-parking-control
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: parking-control
